### ISSUE TITLE
Document need to be updated for Customizing Solr config

### ISSUE THREAD

**Issue by KalpanaGoel** [forumone/web-starter#100]
The documentation at http://forumone.github.io/web-starter/localdev/customization.html is very helpful but not completely accurate.  Here are some suggested updates.

Make it clear that all paths are relative to the repo.  Perhaps this is commentary that should be added for all the documentation somewhere?  The confusion might come in for folks who are working inside the Vagrant box itself and might look for a /puppet directory off of root.

Step 2 has an inaccurate list of the files that need to be specified and copied.  The correct list is:
- elevate.xml
- protwords.txt
- mapping-ISOLatin1Accent.txt
- schema_extra_fields.xml
- schema_extra_types.xml
- schema.xml
- solrconfig_extra.xml
- solrconfig.xml
- solrcore.properties
- stopwords.txt
- synonyms.txt

It should be made clear that all of these files, even if they're not being edited, need to be enumerated in the yaml and copied from the search_api directory into the solr conf directory in the puppet directory.

Please provide info on the correct way to restart Solr after the changes have been provisioned.

Please add a note to remind folks that they will most likely need to re-index unless their changes are only to query-time filters.

Please provide info on the correct way to get these new configuration files deployed on our servers.  At this point it appears we need to coordinate with Mike Shade to get him to copy the files over for us manually?  Whatever the process, it needs to be documented.

**Comment by wwhurley** [comment]
Updated documentation for Solr configuration files. The latter issue isn't really meaningful within this project, I'm afraid.
