### ISSUE TITLE
File permission problems

### ISSUE THREAD

**Issue by azinck** [forumone/web-starter#104]
On a fresh setup of web-starter my sites/default/files directory in my VM was owned by vagrant:games.  PHP was running as nginx, however, which prevented it from creating directories or files in the files directory.

I resolved by setting php-fpm to run as the vagrant user.

I'm not clear as to what the best resoution is.

**Comment by wwhurley** [comment]
I've seen this happen a couple of times. Generally saving the File system form resolves it. I've added more documentation to the [Troubleshooting guide](http://forumone.github.io/web-starter/localdev/troubleshooting.html) with [`#46b3583`](https://github.com/forumone/web-starter/commit/46b358331832ba45fa62834e3a5b1a22bbff7d7a#diff-b7e371403a4adfa098b33601cf9f84a0).
