### ISSUE TITLE
Acquia deprecating PHP < 5.5

### ISSUE THREAD

**Issue by johnbburg** [forumone/web-starter#113]
On September 1, 2015, Acquia will end support for versions of PHP below 5.5. Any systems not using these versions will undergo a forced upgrade. 

This issue is to update versions of php in the [Acquia hosts file](https://github.com/forumone/web-starter/blob/1.1.x/puppet/manifests/hieradata/hosts/acquia.yaml). Note, this will lead to errors in any existing VMs that attempt to re-provision as the installed version of php and the new version will conflict, example:

```
==> default: Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install php55-pecl-xdebug' returned 1: Error: Nothing to do
==> default: 
==> default: Error: /Stage[main]/Forumone::Php/Php::Module[pecl-xdebug]/Package[php55-pecl-xdebug]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install php55-pecl-xdebug' returned 1: Error: Nothing to do
```

The only way around that I know this is to destroy and re-provision the VM.

**Comment by johnbburg** [comment]
Seems that there are some differing naming conventions in some php modules from 5.4 to 5.5

```
==> default: Error: Could not find package php55u-mysql
==> default: Error: /Stage[main]/Forumone::Php/Php::Module[mysql]/Package[php55u-mysql]/ensure: change from absent to present failed: Could not find package php55u-mysql
==> default: Notice: /Stage[main]/Php::Mod_php5/Package[php55u]/ensure: created
==> default: Info: /Stage[main]/Php::Mod_php5/Package[php55u]: Scheduling refresh of Service[httpd]
==> default: Notice: /Stage[main]/Percona::Install/Package[Percona-Server-shared-55]/ensure: created
==> default: Notice: /Stage[main]/Forumone::Varnish/Service[varnish]/ensure: ensure changed 'stopped' to 'running'
==> default: Error: Could not find package php55u-pecl-apc
==> default: Error: /Stage[main]/Forumone::Php/Php::Module[pecl-apc]/Package[php55u-pecl-apc]/ensure: change from absent to present failed: Could not find package php55u-pecl-apc
==> default: Notice: /Stage[main]/Forumone::Php/Php::Module::Ini[apc]/File[/etc/php.d/apc.ini]: Dependency Package[php55u-pecl-apc] has failures: true
==> default: Warning: /Stage[main]/Forumone::Php/Php::Module::Ini[apc]/File[/etc/php.d/apc.ini]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Forumone::Php/Php::Module[pecl-memcached]/Package[php55u-pecl-memcached]/ensure: created
```

There is no php55u-mysql package, should be php55u-mysqlnd

There is no php55u-pecl-apc package, should be php55u-pecl-apcu

These are identified in each puppet/manifests/hieradata/platforms/*.yaml

I'm not sure how we can modify this to easily accommodate 5.5 on demand other than tweaking it on a per-project basis.

**Comment by johnbburg** [comment]
Just brainstorming on a few ideas.

Add a new set of hieradata files for php module names. Map the module's generic name to the specific php version's name? e.g.

```
forumone::php54::mysql
  - mysql

forumone::php55u::mysql
  - mysqlnd
```

I don't really like the idea of adding such a single purpose set of hiera files into the web-starter side though. This seems like something that should be in the puppet-forumone repository, but I don't believe that side is setup to include any sort of hieradata in this way.

Edit: Could just dump it in common.yaml.

**Comment by wwhurley** [comment]
We should probably just change the acquia.yaml file to use php55u for `forumone::php::prefix`. The drupal.yaml is already set to use mysqlnd.

**Comment by wwhurley** [comment]
The only way to switch PHP versions is unfortunately to manually remove the old version prior to re-provisioning. This involves running `yum remove [php prefix]-common` and then exiting and running `vagrant provision`
