### ISSUE TITLE
Allow project specific shell scripts to run at various times

### ISSUE THREAD

**Issue by wwhurley** [forumone/web-starter#12]
Enable capistrano to trigger per-project scripts when certain actions are performed. Examples might include:
- before/after code is deployed
- before/after updates are run
- before/after rollbacks happen

**Comment by slucero** [comment]
An example framework worth looking at is the [build lifecycle](http://docs.travis-ci.com/user/build-configuration/#Build-Lifecycle) used in Travis CI. If the CI jobs look for and execute pre-named scripts at the various points in the process then the scripts could be included as needed in the project repos and customized as needed.
This framework also allows for simple project processes to stay simple with few or no build hook scripts while complex projects could include scripts for all hooks that may even run other separately defined tasks as needed.
Example build hooks could include those defined in the [Travis CI build lifecycle](http://docs.travis-ci.com/user/build-configuration/#Build-Lifecycle) or a facsimile there-of:
- before_install
- install
- after_install
- before_script
- script
- after_success
- after_failure
- after_script

**Comment by slucero** [comment]
Another example approach to a similar functionality: https://github.com/acquia/cloud-hooks
