### ISSUE TITLE
Remove pecl-apc references

### ISSUE THREAD

**Issue by johnbburg** [forumone/web-starter#125]
A recent VM provisioning generated this error:

```
==> default: Error: Could not find dependency Package[php55u-pecl-apc] for File[/etc/php.d/apc.ini]
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Since we have moved to php55, which uses OPcache instead of APC, should we remove all references to APC from the project? such as this one: https://github.com/forumone/web-starter/blob/1.1.x/puppet/manifests/init.pp#L16

**Comment by wwhurley** [comment]
With the change to PHP 5.5 the configuration for APC had been left in the acquia.yaml file. Other host specifications should have already had the APC configuration removed, so it should affect them. Let me know if you were seeing this error on a project using a different host.
