### ISSUE TITLE
Two instances of node_modules will cause '502 Bad Gateway' and Drush 'Segmentation fault (core dumped)'

### ISSUE THREAD

**Issue by lrobeson** [forumone/web-starter#126]
# Symptoms
- any `/admin` path results in a "502 Bad Gateway" error (but _can_ access public pages and _can_ log in)
- `drush cc all` results in `Segmentation fault (core dumped)`
- PHP log contains: `WARNING: [pool www] child 25704 exited on signal 11 (SIGSEGV - core dumped) after 26.884546 seconds`
- nginx log contains: `[error] 5122#0: *8 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 10.0.2.2, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8081"`
# Cause
- `node_modules` directory in the `/sites/all/themes/gesso` directory (mine was there because I had separate Grunt tasks set up in the very beginning of the project)
- I don't think a single instance in the theme caused the issue, I think it's when the project root also contains a node_modules directory. Which in my case didn't happen until last week when we switched over to having Grunt tasks generate the build artifacts (https://redmine.forumone.com/issues/45933).
# Solution
- remove `node_modules` (and `package.json`) from the theme directory and only use the project root's Grunt tasks
# References
- https://drupal.stackexchange.com/questions/126880/how-do-i-prevent-drupal-raising-a-segmentation-fault-when-using-a-node-js-themin/136951
- [Drupal.org issue: Ignore front end vendor folders to improve directory search performance](https://www.drupal.org/node/2329453)
- https://www.karelbemelmans.be/2015/08/weird-errors-with-drupal-themes-containing-a-node_modules-folder/

**Comment by arh1** [comment]
Thanks for writing this up so thoroughly, Laura! Hope it proves useful to other folks.
