### ISSUE TITLE
Gem::InstallError: net-ssh requires Ruby version >= 2.0

### ISSUE THREAD

**Issue by deviantpixel** [forumone/web-starter#127]
I get the following error when I run "bundle install":
Gem::InstallError: net-ssh requires Ruby version >= 2.0

After bring it up with the group it looks like the solution is to add the following to the "/Gemfile" file:
gem 'net-ssh', '~>2.9.2'

Think this change needs to be added to the project to prevent others from hitting the same dependency error. Without this no grunt tasks can run without error.

**Comment by lrobeson** [comment]
Not sure if it's the official solution but I added `gem 'net-ssh', '~>2.9.2' # v3 requires Ruby 2.0` to the project's Gemfile and was able to successfully run `bundle install`.

**Comment by mortona42** [comment]
Why not update ruby?

**Comment by slucero** [comment]
Confirmed on 63c59f5ad49e24fee5aa95a67d564e22d53855fb. I'm hesitant to push out a major update to the Ruby version without testing, so I'll push out the suggested version specification to fix this issue and we'll follow-up on the larger version change in #128.

**Comment by lucia-w** [comment]
I change the version of net-ssh ,and it works well
`group :test, :development do
  gem "rspec-rails", ">= 2.5.0"
  gem 'factory_girl', '2.6.4'
  gem 'factory_girl_rails', '1.7.0'
  gem 'faker', '1.1.2'
  gem 'forgery', '0.5.0'
  gem 'magic_encoding', '0.0.2'
  gem 'email_spec', '1.4.0'

  gem 'net-ssh', '~> 2.0'
  gem 'capistrano', '~> 2.15.7'
  gem 'capistrano-rbenv', '1.0.5'
  gem 'rb-readline','0.4.2'
end`

**Comment by yarhtut** [comment]
@shirlawz it will install net-ssh '2.9.2'
