### ISSUE TITLE
Salt pillar / state structure

### ISSUE THREAD

**Issue by wwhurley** [forumone/web-starter#135]
Needs:
- Ensure settings and states can be grouped by logical purpose, e.g. platform, host, etc.
- Ensure settings and states can be overridden for the specific project without altering these default files

Proposed solution:
- Pillar will include one or more files corresponding to host and platform
- These default files will contain a list of states to be used
- The top.sls will loop through these to construct the list of states to be added on the minion
- The default files will also contains settings used by those states
- There will be some files merged after these default files in order to allow project specific overrides

**Comment by mshade** [comment]
Keep yeoman in mind - states/top.sls and pillars/pillar.sls for site-specific config
