### ISSUE TITLE
Allow local site drush alias to work without entering password

### ISSUE THREAD

**Issue by mortona42** [forumone/web-starter#138]
Here's the current ssh-options for @site.local:
'ssh-options' => "-i ~/.vagrant.d/insecure_private_key -l vagrant",

This key is no longer used by vagrant, so it asks for the vagrant password for every drush command.

Our vagrant ssh keys are now stored as:
IdentityFile /Users/amorton/Sites/web-starter/.vagrant/machines/default/virtualbox/private_key

Since that has my home directory in it, it won't work for other developers.  Let's find a way to share a site alias that works for everyone.

**Comment by mortona42** [comment]
There may be some possible solutions with:

config.ssh.insert_key = false
or
config.ssh.private_key_path = ".vagrant/machines/default/virtualbox/private_key"

(both untested)

Otherwise, I'd look into setting it relative to the site root within the alias file.

**Comment by mortona42** [comment]
Adding config.ssh.insert_key = false to the Vagrantfile does the trick.  I think it essentially reverts back to the pre 1.7 behavior with a shared insecure_private_key.  Is this an acceptable solution?

[vagrant reload] to test config.

**Comment by mortona42** [comment]
[vagrant reload] to test config.

**Comment by mortona42** [comment]
More testing needed - I tried to update an existing site with this but didn't work.

**Comment by wwhurley** [comment]
I believe this has been resolved by #174. Can you verify?

**Comment by mortona42** [comment]
Has been working well lately.
