### ISSUE TITLE
Consider GitBook for documentation

### ISSUE THREAD

**Issue by arh1** [forumone/web-starter#139]
I've been enjoying [GitBook](https://www.gitbook.com/) as a documentation tool lately. Just opening up for conversation: might it be smart to move there for the web-starter docs?

It seems [GitBook](https://www.gitbook.com/) would allow us to consolidate the docs from the wiki for this project and other related projects, and http://forumone.github.io/web-starter/ , into a format that's easier to read, maintain and grow. That said, maybe it's overkill, or maybe the work to convert the existing docs would be too much overhead.

Interested to hear any thoughts.

**Comment by slucero** [comment]
I like the idea of the tool overall and it looks very interesting, but I'm not sure how good a match it is for this project specifically. It looks like the overall structure it enforces is very narrative-based with a push for "chapters" and similar sequencing. @arh1, could you point us to an example of a project similar to ours making effective use of this for documentation?
