### ISSUE TITLE
Clarify roles of `:webroot` and `:app_webroot` variables

### ISSUE THREAD

**Issue by gustavderdrache** [forumone/web-starter#140]
In e.g., [config/deploy/dev.rb](https://github.com/forumone/web-starter/blob/1.1.x/config/deploy/dev.rb#L10-L11), there's a `:webroot` variable set to `'public'`. I made the assumption that's what I needed to change for a non-standard location, but it turns out I actually needed to set the `:app_webroot` variable.

Can we clarify which one of the two is more likely to change, and if it's not `:webroot`, can the example files be updated to use the other?

**Comment by gustavderdrache** [comment]
After discussing this issue with @wwhurley, `:webroot` is the variable that's more likely to change. So it seems like the easiest solution would be to rename `:webroot` to make its intended usage more obvious. I might suggest `:dest_webroot` or `:remote_webroot` or similar.

Thoughts?

**Comment by slucero** [comment]
I like the idea of relabeling this to make the purpose more clear, especially since I was also confused by this. My initial concern around this, however, is backward support and avoiding any breaking changes. A change like this would likely require us to continue mapping `:webroot` to the new variable name behind the scenes in order to avoid breaking deployments for any existing projects since this variable is defined in the `/config` directory where the files are more project-specific and maintainers are likely to be more hesitant to pull in the updates.

**Comment by gustavderdrache** [comment]
Might I suggest a transitional period? Can we determine if a variable is or is not set and issue a warning?

```
if exists(:webroot) and not exists(:dest_webroot) {
    warn ":webroot is going away."
}

set :webroot, fetch(:dest_webroot)
```

Ultimately, yes, backwards compatibility is a thing to keep. Maybe it's best to defer until a major update with a big "WARNING: BREAKING CHANGE!" label on it.

**Comment by slucero** [comment]
> Maybe it's best to defer until a major update with a big "WARNING: BREAKING CHANGE!" label on it.

Conveniently enough we do have one of those coming up with the change from Puppet to Salt. That's gonna break a whole lot of stuff for existing projects trying to transition, so maybe adding another onto the pile would be the best place for it.

**Comment by gustavderdrache** [comment]
That's fine by me.

In the meantime, could we consider changing [this comment](https://github.com/forumone/web-starter/blob/1.1.x/config/deploy/dev.rb#L10-L11) to read "The directory where the webroot exists on the remote server" for those of us who get confused easily?

**Comment by slucero** [comment]
I updated the comment in all of the default files and the template. I've also opened #141 to track the task of relabeling the variable and determining when to introduce that change.
