### ISSUE TITLE
Vagrant-cachier and NFS on Ubuntu derivatives. Heterogeneity

### ISSUE THREAD

**Issue by heddn** [forumone/web-starter#142]
William Hurley: Okay. In the Vagrantfile after line 23, should be something like https://github.com/forumone/web-starter/blob/1.1.x/Vagrantfile#L23, add a comma and then the following:
:linux__nfs_options => ["rw","no_root_squash","no_subtree_check"]
Want to make sure it's aligned with "mount_options" attribute above

William Hurley: And then you'll need to run "vagrant reload" @LucasHedding. Make sense?
BTW, that issue is related to https://github.com/forumone/web-starter/pull/137.

William Hurley: 
I'll probably want to update the Vagrantfile with the same NFS changes that we have in https://github.com/forumone/web-starter/blob/1.1.x/Vagrantfile#L46-L52. Might as well be consistent with our NFS options, after all. Could you open an issue about vagrant-cachier and NFS on Ubuntu derivatives?
Heterogeneity. :(

**Comment by gustavderdrache** [comment]
Having a similar issue with sshd here. I finally got it to stop complaining with these changes:

``` diff
-    nfs_exports = ["rw", "noac", "actimeo=0", "intr", "async", "insecure", "no_subtree_check", "noacl", "lookupcache=none"]
+    nfs_exports = ["rw", "async", "insecure", "no_subtree_check"]
```

**Comment by heddn** [comment]
I've opened #154 to account for the necessary changes on linux.

**Comment by wwhurley** [comment]
Thanks. Pulled in.
