### ISSUE TITLE
Too many open files?

### ISSUE THREAD

**Issue by johnbburg** [forumone/web-starter#143]
After working within a VM for a while, I will begin to see errors due to the site being unable to open files.

```
Fatal error: require_once(): Failed opening required ...
```

I've previously noticed other errors in the past when provisioning "Too many open files" or something to that degree. A vagrant reload seems to resolve this easily enough. I am just filing this issue out of curiosity of what might be causing this and to serve as documentation for others encountering the same issue.

**Comment by ohthehugemanatee** [comment]
Bizarre. I'm experiencing the same problem. `ulimit -n` shows the expected limit of 1024 files open though.

**Comment by johnbburg** [comment]
I've seen that before. vagrant reload usually does the trick. I have no
idea what causes it though.

On Mon, Feb 1, 2016 at 9:08 AM, Campbell Vertesi notifications@github.com
wrote:

> Bizarre. I'm experiencing the same problem. ulimit -n shows the expected
> limit of 1024 files open though.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/forumone/web-starter/issues/143#issuecomment-177987858
> .

## 

John Brandenburg
Senior Developer
Forum One Communications
http://www.forumone.com/ http://forumone.com/
703.894.4362

**Comment by johnbburg** [comment]
Possibly/probably related: https://bugs.xdebug.org/view.php?id=1070, (found in http://superuser.com/a/829413) If that's the case, then upgrading to the newest version xdebug (2.4.0), which should be used by default by any newly provisioned VMs should resolve that issue (assuming these are the same). Any VMs provisioned before the release would need to be destroyed and re-built (but you may be better off just reloading when you need to).

Since we don't have any reliable way of replicating this, I'm going to close the issue, but it's searchable for posterity.
