### ISSUE TITLE
Expand Custom Post-Provision Scripts Into Independent Files

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#144]
## Problem

Currently all custom post-provision scripts are captured in a single file to be executed under `puppet/shell/custom/post-provision.sh`. This works well enough for simple scenarios where a simple set of tasks are consistent and easily selected from the example files provided, but introducing features like database loading (#81) can quickly make this file large and unwieldy.
## Proposed Solution

I propose changing our architecture from the single script model that is currently used: https://github.com/forumone/web-starter/blob/1.1.x/puppet/shell/post-provision.sh#L20-L22

``` bash
if [[ -f "${VAGRANT_CORE_FOLDER}/puppet/shell/custom/post-provision.sh" ]]; then
  source ${VAGRANT_CORE_FOLDER}/puppet/shell/custom/post-provision.sh
fi;
```

To something more modular and extensible, such as putting independent custom tasks in their own files to be executed within `puppet/shell/custom/post-provision.d/`:

``` bash
if [[ -d "${VAGRANT_CORE_FOLDER}/puppet/shell/post-provision.d" ]]; then
  for conf in ${VAGRANT_CORE_FOLDER}/puppet/shell/post-provision.d/*.sh
  do
    source $conf
  done
fi;
```
## Benefits

One advantage of this change is that the files for common tasks become more modular and can be shared more easily. Taking this a step further, these common configurations could also be broken into components that may be included in and selected from the project generator.

**Comment by slucero** [comment]
One difficulty in this approach is maintaining any sequence between tasks to be run. A potential work-around to address this could be for best practice to dictate all tasks are defined as function calls in these files and a final file calls the functions in order after sourcing them from the custom files.

I do worry, however, that this adds more complexity than value and may make this change less desirable. Additional feedback would be appreciated.

**Comment by johnbburg** [comment]
I think scripts can be pretty easily organized within the original Vagrant-loaded script as long as they are loaded separately or there is a clear separation of activities. A robust script loading system may be a bit overkill, and with the introduction of separate scripts that run as root, even slightly more complicated. I think what would be interesting is getting a census of the tasks that people perform in any custom shell script provisioners and try to break these out separate examples which can be individually loaded as desired.

Uses that come to mind:
- Loading database dump stored in S3 (linked above).
- Copying {settings,config}.php files (already included).
- Copy drush aliases file (already included).
- drush.ini tweaks.
  - Increase memory limit  (already included).

I've also had to add scripts that:
- Reset permissions on mysql socket (I had to do this when using non-standard mysql version to mirror a client server).

From a quick poll of the dev team:
- Running common system/drush tasks
  - Clearing memcache
  - Restarting php-fpm
  - Drush site-install
  - Reverting features
  - Clearing caches
  - Grunt build

+More to come as I collect ideas.

I miss you Stephen!

**Comment by wwhurley** [comment]
I'm not sure that having drush commands in the provisioner makes a whole lot of sense. Especially since they are run much more frequently than provisioning is and they serve a different domain.
