### ISSUE TITLE
File Permission Issues on Provisioning

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#151]
After provisioning a machine for the first time, some files are not writable by the web server causing errors in the CMS.

One example:

Mac host machine, Drupal site, Nginx server.
After provisioning `/vagrant/public/sites/default/files` is not writable by nginx because the file and its contents are owned by `vagrant:root` and is not world writable.

**Comment by deviantpixel** [comment]
Think we might have just figured this bug out but it appears with El Capitan. It appears to be the Vagrantfile entry of "maproot=0:0" which appears in different versions of various projects.

The fix has been to just remove "maproot=0:0" from it's occurrence in the Vagrantfile. You must then "vagrant reload" to apply the change.

To test we have been inspecting the /etc/exports file. Before the change specific vagrant entries use "maproot=0:0". After removing it from the vagrant file it uses "mapall=503:20" (userid:user group id) correctly which solves the issue.

**Comment by mshade** [comment]
This should be fixed by my last commit

**Comment by ohthehugemanatee** [comment]
Confirmed fixed for me. I watched the /etc/exports mapall value change through a vagrant reload, to fix exactly this problem. Closing the issue.
