### ISSUE TITLE
Fix for Bundler eventmachine error (Mac users)

### ISSUE THREAD

**Issue by lrobeson** [forumone/web-starter#157]
### Problem

Running `bundle install` on a Mac running El Capitan with Homebrew installed:

```
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

An error occurred while installing eventmachine (1.0.8), and Bundler cannot continue. Make sure that `gem install eventmachine -v '1.0.8'` succeeds before bundling.
```
### Fix

`brew link openssl --force`
### Reason

> "El Capitan no longer provides OpenSSL headers. You'll need to install openssl using either HomeBrew or MacPorts."

Github source: https://github.com/eventmachine/eventmachine/issues/643

**Comment by wwhurley** [comment]
Unfortunately this is beyond the scope of this project to resolve. We expect gems necessary for a project would be installed inside the guest OS not the host.
