### ISSUE TITLE
Extended Server Syntax Documentation: Something that quacks???

### ISSUE THREAD

**Issue by johnbburg** [forumone/web-starter#159]
I've read this paragraph a dozen times. I have no idea what it is trying to say.

https://github.com/forumone/web-starter/blob/1.1.x/config/deploy/dev.rb#L35

Typo? What's the intended meaning?

**Comment by wwhurley** [comment]
Somewhere along the line some of the comment text was removed. Re-added it from the basic Capistrano configuration. Basically it expects something that is like a hash.
