### ISSUE TITLE
Errors on initial vagrant up (Could not find class forumone::webserver for localhost.localdomain on node localhost.localdomain)

### ISSUE THREAD

**Issue by mortona42** [forumone/web-starter#16]
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'f1-centos64-64'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 80 => 8080 (adapter 1)
[default] -- 8080 => 8081 (adapter 1)
[default] -- 8983 => 18983 (adapter 1)
[default] -- 3306 => 13306 (adapter 1)
[default] -- 1080 => 1080 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] The guest additions on this VM do not match the installed version of
VirtualBox! In most cases this is fine, but in rare cases it can
cause things such as shared folders to not work properly. If you see
shared folder errors, please update the guest additions within the
virtual machine and reload your VM.

Guest Additions Version: 4.2.10
VirtualBox Version: 4.3
[default] Configuring and enabling network interfaces...
[default] Mounting shared folders...
[default] -- /tmp/vagrant-puppet/manifests
[default] Exporting NFS shared folders...
Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
[default] Mounting NFS shared folders...
[default] Running provisioner: shell...
[default] Running: /var/folders/n7/1y7hgpqn3_q592mpp54np1vm0000gp/T/vagrant-shell20140613-49068-oy0uqo
[default] Running provisioner: shell...
[default] Running: /var/folders/n7/1y7hgpqn3_q592mpp54np1vm0000gp/T/vagrant-shell20140613-49068-11xknbh
Installing git
Finished installing git
Copied Puppetfile
Installing librarian-puppet
ERROR:  Error installing librarian-puppet:
    activesupport requires Ruby version >= 1.9.3.
Finished installing librarian-puppet
Running initial librarian-puppet
/tmp/vagrant-shell: line 83: librarian-puppet: command not found
Finished running initial librarian-puppet
[default] Running provisioner: puppet...
Running Puppet with init.pp...
WARN: Fri Jun 13 17:45:38 +0000 2014: Not using Hiera::Puppet_logger. It does not report itself to be suitable.
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Hiera YAML backend starting
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Looking up classes in YAML backend
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Looking for data source sites/localhost.localdomain
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Looking for data source platforms/drupal
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Found classes in platforms/drupal
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Looking for data source hosts/f1dev
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Found classes in hosts/f1dev
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Looking for data source common
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Found classes in common
Error: Could not find class forumone::webserver for localhost.localdomain on node localhost.localdomain
Error: Could not find class forumone::webserver for localhost.localdomain on node localhost.localdomain
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

FACTER_host_uid='502' FACTER_host_gid='20' FACTER_vagrant_user='amorton' puppet apply --verbose --hiera_config=/tmp/vagrant-puppet/hiera.yaml --manifestdir /tmp/vagrant-puppet/manifests --detailed-exitcodes /tmp/vagrant-puppet/manifests/init.pp || [ $? -eq 2 ]

Stdout from the command:

Stderr from the command:

WARN: Fri Jun 13 17:45:38 +0000 2014: Not using Hiera::Puppet_logger. It does not report itself to be suitable.
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Hiera YAML backend starting
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Looking up classes in YAML backend
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Looking for data source sites/localhost.localdomain
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Looking for data source platforms/drupal
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Found classes in platforms/drupal
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Looking for data source hosts/f1dev
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Found classes in hosts/f1dev
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Looking for data source common
DEBUG: Fri Jun 13 17:45:38 +0000 2014: Found classes in common
Error: Could not find class forumone::webserver for localhost.localdomain on node localhost.localdomain
Error: Could not find class forumone::webserver for localhost.localdomain on node localhost.localdomain

**Comment by wwhurley** [comment]
It appears this was caused by an update in librarian-puppet in response to rodjek/librarian-puppet#210. Looks like we'll have to specify the version of librarian until we can get the system version of Ruby updated.

**Comment by johnbburg** [comment]
Was this supposed to make it into the 1.1.x branch?

**Comment by wwhurley** [comment]
This issue is over 2 years old. Newer issues that may have the same symtoms -- the issues pulling with Librarian -- have a different solution. Namely updating Ruby with the new `librarian-puppet-install.sh` script.

**Comment by johnbburg** [comment]
Whoops. Just read the June and skipped over the year.  Thanks.
