### ISSUE TITLE
Composer install needs sudo

### ISSUE THREAD

**Issue by mortona42** [forumone/web-starter#160]
When vagrant installs composer, it fails.

Once the vm is booted, this will install composer:
curl -sS https://getcomposer.org/installer | php

But with the arguments vagrant uses, it needs sudo:
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

Screenshot of output:
http://i.imgur.com/r2BDfSf.png

**Comment by wwhurley** [comment]
Puppet exec command runs as root. See https://github.com/forumone/puppet-forumone/blob/1.1.x/manifests/composer.pp#L6-L12. There was an issue with the COMPOSER_HOME environment variable not being set during the composer installation. This was added on 1.1.33. What version is in your Puppetfile?

**Comment by mortona42** [comment]
web-starter currently uses 1.1.31, so I have that.

**Comment by wwhurley** [comment]
It would probably help if I update the version there after I update the Puppet module.
