### ISSUE TITLE
NFS Drama

### ISSUE THREAD

**Issue by gustavderdrache** [forumone/web-starter#168]
Attempting to use a Drupal upload module [file_resup](http://drupal.org/project/file_resup) resulted in a number of inexplicable errors. The issue was eventually solved by switching to shared folders instead of NFS entirely.

To no one's surprise, my host machine is Linux.

**Comment by wwhurley** [comment]
I think we've chanced upon the set of magic incantations for NFS for both Darwin and Linux.
