### ISSUE TITLE
Host ssh keys fail to forward to vm

### ISSUE THREAD

**Issue by mortona42** [forumone/web-starter#17]
In my host's ssh config, I have:
Host *
ForwardAgent yes

In my vagrant box, this fails to successfully use the keys unless I put this in the VM's ssh config:
GSSAPIAuthentication no
AddressFamily inet

I'm not sure why this is necessary, but it seems to work, and I'd like to see it configured this way by default if it solves the problem for everyone.

**Comment by wwhurley** [comment]
I believe you mentioned you resolved this and it was due to some configuration issue on your host. Could you provide more information?
