### ISSUE TITLE
Create drupal8 hiera platform, deploy script

### ISSUE THREAD

**Issue by ohthehugemanatee** [forumone/web-starter#184]
Drupal 8 has some different requirements, and a different deploy process. This should be a hiera/yeoman option for platform=drupal8. Off the top of my head:
- Merge in [drupal-composer](https://github.com/drupal-composer/drupal-project), simlink vendor/bin/drupal and vendor/bin/drush to /usr/local/bin
- Use `/vagrant/web` as the docroot (we could symlink, but that confuses PHPStorm into thinking there are two resource roots... and probably other IDEs too)
- Solr 5.x (or maybe 4.x, depends on the status of search_api_solr in 8)
- PHP 5.6 (I understand 7.x doesn't have great contrib support, but we should ask @heddn )
- [Different varnish vcl](http://www.jeffgeerling.com/blog/2016/use-drupal-8-cache-tags-varnish-and-purge)
- Gesso version, status, and requirements are all a bit different.
- Different build, install, CI prep process. ("composer install && drush si --profile=mysite") This is mostly taken care of by depending on drupal-composer, but we'll need a drupal8.rb for our capistrano steps.

**Comment by heddn** [comment]
Based on https://www.drupal.org/node/2607222, PHP 7 is a fine platform to use as a default. I've been using it a while on D8 and haven't run into any notable issues.

**Comment by wwhurley** [comment]
Why would we be changing the docroot to `web`?

**Comment by ohthehugemanatee** [comment]
because that's the docroot for drupal-composer - see [their issue on the subject](https://github.com/drupal-composer/drupal-project/issues/64). "web" is the normal web root for Symfony apps, including the [Symfony Standard](https://github.com/symfony/symfony-standard), which is why drupal-composer uses it.

If we want to stick with public, the alternatives are:
- Symlink public to web, and configure phpstorm et al to ignore one of the roots.
- Change the webroot we get from drupal-composer. That requires changes in composer.json (several locations), .gitignore (several locations), and post-install.sh (only DOCROOT variable at top of the script).
