### ISSUE TITLE
Composer in root of project

### ISSUE THREAD

**Issue by heddn** [forumone/web-starter#185]
With drupal-composer/drupal-project, behat and other development that is using composer, not to mention the many places where we are starting to use composer manager for various modules... and the advent of D8 development on the horizon, let's standardize on putting a composer.json in the root of the webstarter project.

**Comment by generalconsensus** [comment]
I support this move, with the caveat that we take this time to integrate BDD/TDD tests under one folder (example: /test/simpletest /tests/behat /tests/karma/)

**Comment by heddn** [comment]
Although the location of tests/foo is irrelevant. Because where that is in relation to the vendor files is somewhat non-connected. But I'll support it if we can come to some conclusion here.

**Comment by mortona42** [comment]
Don't forget to add the vendor directories to the .gitignore.  Dan added tests/behat/vendor since behat is added via composer.  I think if we just have "vendor" that will apply to all directories by that name.

**Comment by heddn** [comment]
Blindly ignoring vendor is a bad idea. There are some modules that pre date composer that use such a named folder.

**Comment by mortona42** [comment]
Ok, good to know.

**Comment by fafnirical** [comment]
I'd suggest we create one in the templates directory of [forumone/generator-web-starter-drupal](https://github.com/forumone/generator-web-starter-drupal) instead of in here.
