### ISSUE TITLE
Error: bundle returned 5 instead of one of [0]

### ISSUE THREAD

**Issue by mortona42** [forumone/web-starter#187]
![screen shot 2016-04-06 at 9 18 29 am](https://cloud.githubusercontent.com/assets/696005/14324172/9eea358a-fbd8-11e5-8cdd-0b5f24cdc193.png)

I updated the generator before starting, selected wordpress and puppet.

**Comment by johnbburg** [comment]
@mortona42 What is the output of `$ gem install mime-types-data -v '3.2016.0221'` from within the VM? I think I ran into something similar the other day. That version of the gem required ruby 2+ or something like that. I think updating the Gemfile to the current version in web-starter and then re-generating gemfile.lock resolved the issue.

**Comment by mortona42** [comment]
[vagrant@localhost ~]$ gem install mime-types-data -v '3.2016.0221'
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /usr/lib/ruby/gems/1.8 directory.

**Comment by wwhurley** [comment]
You may need to update the project Gemfile. See https://github.com/forumone/web-starter/blob/1.1.x/Gemfile.

**Comment by mortona42** [comment]
I got this last week with a fresh checkout of web starter, filed this bug so it could get fixed here.  I'm not familiar with ruby and how it's installing gems, or I'd help with a patch.

**Comment by wwhurley** [comment]
There was an issue that I had not updated the Gemfile in the generator when the Gemfile in this project had been.

**Comment by mortona42** [comment]
Should this be working now?  I just tried again with a freshly generated yeoman instance, and still getting the error.

**Comment by mortona42** [comment]
Ok, so I just realized that the option to update web starter generator via yeoman doesn't actually work.  I had to do a pull in the generator-web-starter repo directory.

**Comment by mortona42** [comment]
The generator is working fine now, and we can copy the Gemfile to fix existing sites if needed.
