### ISSUE TITLE
Consider separate repos for project scaffolds

### ISSUE THREAD

**Issue by ohthehugemanatee** [forumone/web-starter#189]
One persistent area of complexity in web-starter is scaffolding for different platforms (Drupal X, Wordpress, etc). When it happens, how it happens, and to what degree it happens, are different per platform. They also require pretty detailed investigation and understanding of the platforms, and should track industry best practices quite closely. 

Supporting scaffolding scripts for _n_ potential platforms is a big load of maintenance and potential bike shed problems. It's a lot of us trying to learn and track industry best practices as we have time. And it makes web-starter less generally useful - every platform we add to our "supported" stack makes web-starter more monolithic, more prejudiced, and less generally useful... even within Forum One use cases.

**I propose separating out platform scaffolding into separate repos.** Have individual repos for the Drupal 7, Drupal 8, Wordpress, AngularJS scaffolds, and so on. 

Here are the benefits I see:
- Make web-starter more focused and less monolithic, and therefore easier to maintain.
- Make web-starter more generalized, therefore more useful for more people... and more likely to get external contributors.
- Make the yeoman generator simpler and clarify its scope
- Make forum one's puppet repo simpler and clarify its scope
- Clarify and standardize where and how platform build steps happen.
- Reduce and localize variance between projects
- Allow us to leverage community-maintained scaffolds, like drupal-composer (7 and 8!), automatically inheriting community best practices. If we need to customize a community scaffold, we can fork it to get many of the same benefits.

I can think of a few different ways to do this... but first we have to agree on the principle. Thoughts?

**Comment by wwhurley** [comment]
Some of this is happening with the Yeoman generator where we're decomposing things into separate sub-generators. My thought is that this is where these things will happen more than the larger repository.

**Comment by ohthehugemanatee** [comment]
That makes sense. So yeoman will make a composite version of our VM, with appropriate platform scaffolding.

So I guess step 1 is to move platform scaffolding for our already-supported platforms from web-starter into yeoman-generator... right? Do we already have a structure for that in yeoman-generator, or is there a pre-step of defining the structure?
