### ISSUE TITLE
Install Ruby using pre-compiled binaries

### ISSUE THREAD

**Issue by wwhurley** [forumone/web-starter#191]
See https://blog.packager.io/posts/13-one-liner-to-get-a-precompiled-ruby-on-your-own-servers

**Comment by mshade** [comment]
initial support commited to salt branch in 'ruby' state. defaults to ruby 2.3.0 patch 0. Version can be specified via pillar:

```
ruby:
  version: 2.0.0
  pkg_hash: md5=..... (md5 of tarball)
```

Be aware that ruby:version is already defined in defaults.sls pillar for use with rbenv. Comment out or set to desired binary version listed here: https://packager.io/documentation/ruby/

**Comment by mshade** [comment]
todo:
- check currently installed version and replace if mismatch, though not sure this is worth effort since a destroy/reprovision would also fix
- symlink into .rbenv/versions
- test with gem installs
