### ISSUE TITLE
Can't boot with Pantheon host

### ISSUE THREAD

**Issue by mortona42** [forumone/web-starter#194]
Error: Could not find package php56u-pecl-apc

![screen shot 2016-04-17 at 2 07 51 pm](https://cloud.githubusercontent.com/assets/696005/14590103/b39c1610-04a7-11e6-959e-41187b3ad3a9.png)

Warning: /Stage[main]/Forumone::Php/Service[php-fpm]: Skipping because of failed dependencies
Warning: /Stage[main]/Nginx/Service[nginx]: Skipping because of failed dependencies

**Comment by wwhurley** [comment]
PHP 5.6 uses Opcache. Other cacing modules like XCache and APC have not
been updated to 5.6. Was there a particular setup that Git you that
combination of settings?

On Sun, Apr 17, 2016, 5:20 PM Andrew Morton notifications@github.com
wrote:

> Error: Could not find package php56u-pecl-apc
> 
> (
> https://cloud.githubusercontent.com/assets/696005/14590038/d01b3e30-04a5-11e6-8f16-77cf9ba33dd6.png
> )
> 
> Warning: /Stage[main]/Forumone::Php/Service[php-fpm]: Skipping because of
> failed dependencies
> Warning: /Stage[main]/Nginx/Service[nginx]: Skipping because of failed
> dependencies
> ![screen shot 2016-04-17 at 2 07 51 pm]
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/forumone/web-starter/issues/194
> 
> ## 
> 
> _William Hurley_
> Chief Technology Officer

whurley@forumone.com
www.forumone.com
703.894.4346

_Forum One__:_ Extend Your Influence

**Comment by mortona42** [comment]
I think it was actually the pantheon host selection, I wasn't able to use 5.5 either.

I changed to f1 dev and it's working now.  This is just for trying out some wordpress stuff.

**Comment by wwhurley** [comment]
Sounds like some of the platforms have incompatible PHP modules. Have to
take a look at that.

On Sun, Apr 17, 2016, 5:50 PM Andrew Morton notifications@github.com
wrote:

> I think it was actually the acquia host selection, I wasn't able to use
> 5.5 either.
> 
> I changed to f1 dev and it's working now. This is just for trying out some
> wordpress stuff.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/forumone/web-starter/issues/194#issuecomment-211121059
> 
> ## 
> 
> _William Hurley_
> Chief Technology Officer

whurley@forumone.com
www.forumone.com
703.894.4346

_Forum One__:_ Extend Your Influence
