### ISSUE TITLE
Allow for different versions of SOLR (read 4.0)

### ISSUE THREAD

**Issue by generalconsensus** [forumone/web-starter#198]
Allow for custom installation of SOLR within web-starter.

Ran into this issue with search_api requiring SOLR 4.0: https://www.drupal.org/node/2711381

**Comment by wwhurley** [comment]
This is already configurable using the forumone::solr::version variable. I
would recommend adding that to the localhost.localdomain. yaml file. It is
the full semantic version, e.g. 4.8.0.

On Fri, May 6, 2016, 6:30 PM Daniel McDermott notifications@github.com
wrote:

> Allow for custom installation of SOLR within web-starter
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/forumone/web-starter/issues/198
> 
> ## 
> 
> _William Hurley_
> Chief Technology Officer

whurley@forumone.com
www.forumone.com
703.894.4346

_Forum One__:_ Extend Your Influence
