### ISSUE TITLE
Vagrant Provision Error - Ruby Version

### ISSUE THREAD

**Issue by windycitymoon** [forumone/web-starter#200]
On vagrant up, the box is failing here

`==> default: Error: tar -zxvf /tmp/vagrant-cache/ruby-1.9.3.tgz -C /home/vagrant/.rbenv/versions/1.9.3 returned 2 instead of one of [0]
==> default: Error: /Stage[main]/Forumone::Ruby/Exec[forumone::ruby::extract]/returns: change from notrun to 0 failed: tar -zxvf /tmp/vagrant-cache/ruby-1.9.3.tgz -C /home/vagrant/.rbenv/versions/1.9.3 returned 2 instead of one of [0]
==> default: Info: Creating state file /var/lib/puppet/state/state.yaml
==> default: Notice: Finished catalog run in 218.69 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

**Comment by windycitymoon** [comment]
Side Note: Nothing is being put into the /tmp/vagrant-cache/ during build.

**Comment by windycitymoon** [comment]
the directory /tmp/vagrant-cache was not given full write permissions during the initial vagrant build. 
I changed permissions on that directory to 777, ran a 'vagrant provision' and now it works.

**Comment by mshade** [comment]
To know what went wrong, we'd need to see who owns /tmp/vagrant-cache - can you do ls -ld /tmp/vagrant-cache ?

**Comment by wwhurley** [comment]
I believe this is resolved by https://github.com/forumone/puppet-forumone/commit/996beb8420f23919199635205706684dc11edd99. Previously it was trying to set permissions on that file to vagrant / games (501 / 20) which caused issues.
