### ISSUE TITLE
rbenv: version `1.9.3-p484' is not installed

### ISSUE THREAD

**Issue by mortona42** [forumone/web-starter#204]
I followed William's email and updated my puppet-forumone to 1.1.42 and reprovisioned.  I got this error:

```
==> default: Installing bundler gems
==> default: rbenv: version `1.9.3-p484' is not installed (set by /vagrant/.ruby-version)
```

**Comment by mortona42** [comment]
The version of ruby I got is:
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]

**Comment by wwhurley** [comment]
With the change to pre-compiled versions of ruby the `.ruby-version` file needs to be updated as shown in https://github.com/forumone/web-starter/commit/c7fbe9b04d90bfebb6453dd799f36788de8a5358.

**Comment by mortona42** [comment]
This is the error I see now:

```
==> default: Installing bundler gems
==> default: rbenv: bundle: command not found
```

**Comment by mortona42** [comment]
I did a vagrant destroy this time before I provisioned, but still got the error.  Should I update all of webstarter instead?
