### ISSUE TITLE
Update to use newer version of Java

### ISSUE THREAD

**Issue by wwhurley** [forumone/web-starter#208]
ElasticSearch requires at least Java 7. See elastic/elasticsearch#6313.

**Comment by mshade** [comment]
Created java-formula which defaults to java-openjdk-1.8. Can set specific package name via pillar with

```
java: java-openjdk-1.7.0
```

Also updated solr formula to include this state as a dependency. This means existing projects using the solr formula must add the java formula to salt/minion gitfs and file_roots.

**Comment by mshade** [comment]
#0d9036f

**Comment by mshade** [comment]
commit #2754a4e
