### ISSUE TITLE
XDebug

### ISSUE THREAD

**Issue by wwhurley** [forumone/web-starter#21]
Option to install XDebug package from PECL. Settings should include:

xdebug.remote_enable: 1
xdebug.remote_connect_back: 1
xdebug.remote_handler: "dbgp"

**Comment by mshade** [comment]
actions: 

add ini bits to php conf defaults, add xdebug to php package list

**Comment by mshade** [comment]
Support for custom php.ini, xdebug, and xdebug settings added
