### ISSUE TITLE
503 error; no database server present

### ISSUE THREAD

**Issue by klatovak** [forumone/web-starter#220]
This was first seen on an existing project that I was setting up for the first time locally. I subsequently ran it again with the base web-starter project and got the same results. I ran "yo web-starter" to update the project and then ran "vagrant up". Once the provisioning was complete (assuming it actually did complete) and I visited localhost:8080 I get the following error:
<img width="484" alt="screen shot 2016-06-24 at 9 06 29 am" src="https://cloud.githubusercontent.com/assets/1305268/16343413/de4dfc38-39eb-11e6-8021-a0bdb321d1fc.png">

Although it didn't look to be anything related to the database server, I thought perhaps syncing down the stage db to my local might fix this. Once I ssh'd into the vagrant box, I noticed the mysql server just wasn't there:

```
[vagrant@localhost ~]$ mysql -v
-bash: mysql: command not found
```

Running "vagrant provision" did not correct this, so I reran whole process to get debugging output. Both that and the terminal output is attached.

[terminal-output.txt](https://github.com/forumone/web-starter/files/332131/terminal-output.txt)

[vagrant-debug.txt](https://github.com/forumone/web-starter/files/332126/vagrant-debug.txt)

**Comment by wwhurley** [comment]
This is related to #219.
