### ISSUE TITLE
NPM install fails after fresh provision

### ISSUE THREAD

**Issue by mortona42** [forumone/web-starter#227]
The provision doesn't complain, but on deployment, I got the error about no compatible version of generator-web-starter found.

![screen shot 2016-06-24 at 4 50 49 pm](https://cloud.githubusercontent.com/assets/696005/16353221/0f43d408-3a2c-11e6-8b68-a606ef5ea9c5.png)
![screen shot 2016-06-24 at 4 50 44 pm](https://cloud.githubusercontent.com/assets/696005/16353223/12525228-3a2c-11e6-85fe-f3da0b354d07.png)

**Comment by wwhurley** [comment]
Resolved by pushing up a new version of the generator.
