### ISSUE TITLE
Install gcc and gcc-c++ that supports C++ 12

### ISSUE THREAD

**Issue by wwhurley** [forumone/web-starter#229]
Install gcc 4.8 in order to allow compilation of Node plugins.

**Comment by mshade** [comment]
Created an SCL formula that takes a simple list of packages from project.sls pillar. This allows for arbitrary addition of SCL packages. The list it looks for is scl_packages

Packages from the SCL are then activated ad-hoc. Any time you call a command (from post provision?) that requires an SCL package, you need to enable the SCL. This helps avoid the trouble with globally enabling these packages and conflicts like the `sudo -e` fiasco.

```
$ scl enable devtoolset-3 'gcc --version'
gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)
```

`scl -l` provides a list of installed collections that can be enabled.

**Comment by mshade** [comment]
Pinging for feedback
