### ISSUE TITLE
Solr version

### ISSUE THREAD

**Issue by wwhurley** [forumone/web-starter#23]
Allow variable to select which version of Solr to install, this should download the appropriate package, uncompress it to an appropriate location and install an init.d script to manage it.

**Comment by wilsontech** [comment]
I've added a solr-formula, only slightly changed from the existing solr state we use from the saltmaster. This formula should hopefully replace that one, working for both web-starter and our salt deployments.

https://github.com/forumone/solr-formula

Needs testing.
