### ISSUE TITLE
Fix for SSH Auth issues

### ISSUE THREAD

**Issue by generalconsensus** [forumone/web-starter#237]
"default: Warning: Authentication failure. Retrying"

Ran into an issue with my local file system not having the correct permissions which made logging into vagrant boxes impossible via ssh. Added information to the wiki

**Comment by dcmouyard** [comment]
Is there an automated fix for this issue? It’s annoying to have to ssh into the vm and update the perms manually for each new project.

**Comment by generalconsensus** [comment]
Waiting on next vagrant release to fix

**Comment by generalconsensus** [comment]
This is fixed in latest Vagrant offering
