### ISSUE TITLE
Solr collection

### ISSUE THREAD

**Issue by wwhurley** [forumone/web-starter#24]
Allow creation of Solr collections through Salt. Configuration should allow providing a name, which depending on the version of Solr will update solr.xml (3.6) or create a collection and write to the solrcore.properties file (4.x).

**Comment by mshade** [comment]
Would you mind a short meeting to discuss what's involved in this?

**Comment by mshade** [comment]
Collection created, need to add override via pillar for custom configuration if not defaulting to search-api module

**Comment by wilsontech** [comment]
solr-formula updated and ready for testing. web-starter currently set to pull solr.v4 in roots/states/top.sls, and include java-1.8.0-openjdk in roots/pillars/pillar.sls

v3 should work also.

I'll be testing both a bit further with fresh installs now though.

If solr-formula seems to be working right, next step is a branch or tag created and web-starter updated to pull that remote.
