### ISSUE TITLE
Allow installation of npm packages globally

### ISSUE THREAD

**Issue by wwhurley** [forumone/web-starter#245]
Depending on the VM it may require Grunt, Bower or other packages installed globally.

**Comment by mshade** [comment]
Salt method to install npm packages globally from a list in pillar

**Comment by mshade** [comment]
Added an npm-install state to the node formula that reads a list in the pillar. Added example pillar data to project.sls and the state in states/top.sls to call the npm install

**Comment by mshade** [comment]
Pinging for any feedback before web-starter checkin today
