### ISSUE TITLE
Upgrading to PHP7

### ISSUE THREAD

**Issue by generalconsensus** [forumone/web-starter#249]
I see how to switch the version of PHP so I can upgrade to PHP7. Should I uninstall the previous version of php with pre-provision.sh?

**Comment by wwhurley** [comment]
The previous version of PHP is not removed by changing the version in Hiera. We typically recommend that the machine is destroyed and re-created, though the previous version can be removed by running `sudo yum remove [php prefix]-common` from the command line or a `pre-provision.sh` file. You might need to watch out for a non 0 return halting the provisioning if the package is not installed.
