### ISSUE TITLE
Varnish configuration

### ISSUE THREAD

**Issue by wwhurley** [forumone/web-starter#25]
Allow the ability to specify a default.vcl file to use.

**Comment by mshade** [comment]
https://github.com/forumone/puppet-forumone/commit/18345445c94974fbc1d282d4948d29906a5d3b64

**Comment by wilsontech** [comment]
this should be resolved, but exact commit i believe got lost in the code transfer from RAM.

**Comment by wilsontech** [comment]
Sorry. What was resolved was just the xdebug cookie passing through varnish. Am going to assign to Mike and regroup with him re specifying a specific vcl.

**Comment by mshade** [comment]
Custom vcl support added in 72bd3ea

Custom VCL goes into config/custom/varnish
