### ISSUE TITLE
Wordpress linked_dir(s) and Wordfence

### ISSUE THREAD

**Issue by johnbburg** [forumone/web-starter#253]
First, where does the linked_dir value come from when using Wordpress? It seems to correctly use 

```
set :linked_dirs, %w[public/wp-content/uploads public/wp-content/upgrade]
```

For Wordpress, but looking at the [template](https://github.com/forumone/web-starter/blob/1.1.x/config/_deploy.rb#L42), it only seems to provide options specific to Drupal (unless I manually set these and then forgot I did).

Second, for Wordpress installations, would it be possible to add `public/wp-content/wflogs`? This is a logging directory added by the [Wordfence](https://wordpress.org/plugins/wordfence/) plugin, which will add files by the Webserver, which causes subsequent jobs to error when it can't remove them due to ownership/permissions.

**Comment by johnbburg** [comment]
I've created https://github.com/forumone/web-starter/tree/253-wflogs which should get started in addressing this. I'm taking a guess that {{#is_wordpress}} is a valid value. This branch is untested.

Link to commit: https://github.com/forumone/web-starter/commit/18ebf343e6bb1a7966d88f1774137fb16d9ab0e3

**Comment by wwhurley** [comment]
This is now handled by the generator. See https://github.com/forumone/generator-web-starter-wordpress/blob/master/web-starter/index.js#L110 and  https://github.com/forumone/generator-web-starter-capistrano/blob/master/web-starter/templates/config/deploy.rb#L56

**Comment by johnbburg** [comment]
Ok, that clears up a lot for me. Should we remove _deploy.rb from this repository to prevent confusion?

**Comment by johnbburg** [comment]
Pull request: https://github.com/forumone/generator-web-starter-wordpress/pull/7

**Comment by johnbburg** [comment]
Side question, how can we use the :app_webroot value in these templates? That's been bugging me on projects that use different web-roots.

**Comment by johnbburg** [comment]
I'll close this and start a new issue about the :app_webroot question.
