### ISSUE TITLE
Forward ports for browsersync

### ISSUE THREAD

**Issue by dcmouyard** [forumone/web-starter#263]
The following ports need to be forwarded in order for browsersync to run inside the vm and work on the host machine: 3000, 3001, and 3002.

**Comment by johnbburg** [comment]
Hey Dan,

I'm also looking into setting up browser sync in the VM. I've added the port forwarding like you've done in the pull request, but the browsersync server doesn't seem accessible from my host machine. 

```
 $ curl -v http://localhost:3000/browser-sync/browser-sync-client.js
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /browser-sync/browser-sync-client.js HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.50.1
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

I am able to hit that URL from within the VM. Are there any other steps you had to make to get browsersync working? I am wondering if there is an issue with using vagrant to forward a port before anything is actually listening on that port.

**Comment by dcmouyard** [comment]
I think you need to use the non-varnished server (localhost:8080) as the proxy target in the BrowserSync config.

Here’s the BrowserSync Gulp task that worked for me: https://github.com/forumone/gesso/pull/63/files#diff-dda7df6045f289bbe63bb43f74b3b28d

I believe Derek did something similar for Grunt in the WordPress version of Gesso, but I don’t know the specifics there.

**Comment by johnbburg** [comment]
Possibly related: https://github.com/BrowserSync/browser-sync/issues/318

**Comment by lrobeson** [comment]
+1 for BrowserSync support. I had it working back in the day but it no longer does. :(

Oh wait, I have a PR for this, which is now probably way outdated: https://github.com/forumone/web-starter/pull/130.

**Comment by coreylafferty** [comment]
Here is @windycitymoon's PR to Gesso for WordPress that adds browsersync.  I've tested it and it works outside of Vagrant (not inside).  The only issues I see are 1) it uses watch instead of simple-watch and 2) the path to watch for Pattern Lab files can't use the theme path variable from the package.json file.  If you do use that variable, it will not detect new files (altho oddly it does detect changes to existing files).

https://github.com/forumone/gesso-wp/pull/39

**Comment by generalconsensus** [comment]
+1 Browsersync

**Comment by lrobeson** [comment]
I have this PR submitted, fyi: https://github.com/forumone/web-starter/pull/273. (And @coreylafferty, it still uses simple-watch. I _will_ have to fix the theme path variable though, bummer.)

**Comment by lrobeson** [comment]
@dcmouyard I updated [my PR](https://github.com/forumone/web-starter/pull/273/) with the 2 other ports you said need forwarding (I haven't had issues without them, but if you say they're needed, you're probably right.) :)

**Comment by johnbburg** [comment]
Another FYI, any VMs using the forumone/centos64-64 base box will need to have their iptable rules lifted to allow access to those ports by your host machine. This is the older box, but is still probably used on most projects. The bento/centos-6.8 base box, which is now the default in web-starter, shouldn't have this problem.
