### ISSUE TITLE
Remove sass tasks

### ISSUE THREAD

**Issue by mortona42** [forumone/web-starter#268]
AFAICT the default tasks should all come from gesso.  The ones we have in here are out of date - we should remove them from web-starter, and copy from the theme dir as part of our project scaffolding.

**Comment by mortona42** [comment]
Also, append the devDependencies from the theme's package.json to the root's package.json.  We should remove the existing dependencies from there.

**Comment by wwhurley** [comment]
Not all tasks are related to theming. Some are related to JavaScript development and there will also likely be tasks in the future that automate certain development operations such as pulling down the staging database, reverting Features, etc.

**Comment by mortona42** [comment]
@wwhurley I changed the ticket to just remove sass tasks.  However, I don't see any non sass tasks in here, which ones am I missing?

**Comment by mortona42** [comment]
I just noticed that many dependencies in package.json are added via the generator.  I think it's much easier for our FEDs to manage these by updating in the theme repo, rather than in the generator.
