### ISSUE TITLE
Updating Solr to 4.7.1

### ISSUE THREAD

**Issue by ghost** [forumone/web-starter#27]
Whenever you need to update the version of Solr from the current version which is probably 4.4.0 to something newer like 4.7.1 you will generally receive an error message stating that it cant load the solrconfig.xml file.

The solution to fix this is to do the following from the terminal window.

vagrant ssh
sudo su -
cd /root
rm -fr  solr-webapp
service solr restart

What this does is remove the old version of the solr-webapp directory and then by restarting the solr service it will rebuild the solr-webapp directory with the correct file and allow Solr to load the proper configuration files.

**Comment by fafnirical** [comment]
Pretty sure this is fixed in the latest version of web-starter. I'm running 4.10.4 without any error messages.
