### ISSUE TITLE
VM hangs on startup when host has no network connection

### ISSUE THREAD

**Issue by ohthehugemanatee** [forumone/web-starter#28]
Discovered this on an airplane today. Vagrant can never manage to connect to the VM via SSH, NFS doesn't mount, and in general it acts like networking is busted. I can access the VM via HTTP, but get a 404 since the /vagrant directory isn't mounted.

If I start the VM in VirtualBox I can log in via the console and see that the machine starts properly. There is one failure trying to compile a kernel module on startup - it goes by too quickly for me to read properly but doesn't seem related here. 

In the host machine's log, "vagrant up" produces:

<pre>
8/5/14 8:00:37.000 PM kernel[0]: VBoxNetFlt: was detached from 'vboxnet2' (0)
8/5/14 8:00:37.000 PM kernel[0]: VBoxDrv: host_vmxoff -> vmx_use_count=0
8/5/14 8:00:43.539 PM VirtualBox[61971]: modalSession has been exited prematurely - check for a reentrant call to endModalSession:
8/5/14 8:00:45.477 PM Dock[355]: find_shared_window: Invalid depth WindowID 0x209b
8/5/14 8:00:49.000 PM kernel[0]: VBoxDrv: host_vmxon  -> vmx_use_count=1 rc=0
8/5/14 8:00:49.000 PM kernel[0]: VBoxDrv: host_vmxoff -> vmx_use_count=0
8/5/14 8:00:49.000 PM kernel[0]: VBoxFltDrv: attached to 'vboxnet2' / 0a 00 27 00 00 02
8/5/14 8:00:49.000 PM kernel[0]: VBoxDrv: host_vmxon  -> vmx_use_count=1 rc=0
8/5/14 8:00:49.000 PM kernel[0]: vboxnet2: promiscuous mode enable failed
8/5/14 8:00:49.000 PM kernel[0]: VBoxNetFlt: Failed to put 'vboxnet2' into promiscuous mode, err=102 (0->0)
</pre>

**Comment by wwhurley** [comment]
I was unable to reproduce this behavior. I disabled wireless networks and started a VM and it was able mount the NFS share, secure a local IP address and be map the ports successfully. Can you try reproducing?
