### ISSUE TITLE
Install Drush alias and ini files if available

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#29]
Often-times the deployment process can run out of memory on some of the more resource-intensive processes like large feature reverts. One solution for overcoming this is to install a drush.ini file in ~/.drush on the deployment server to circumvent this.
Ensuring this and alias files are installed in the ~/.drush folder could be worked into the capistrano deployment script to ensure these files are properly available during command executions and various custom scripts that may be run during the process.
During this step in the Capistrano task it could check if either of these files are available (drush.ini, <:application>.aliases.drushrc.php) and copy/symlink them appropriately only if they are present.

**Comment by wwhurley** [comment]
This is already in place in the custom post-provision script. See 42c13a6709b5418c7279e191537edc57c3dcad61.

**Comment by lrobeson** [comment]
I still have to manually copy the aliases file to ~/.drush when I first start a project. Is that supposed to have been fixed?

**Comment by wwhurley** [comment]
The particular project probably has not installed the custom post-provision.sh file. Inside puppet/shell/custom there are examples for both Drupal and WordPress and can serve as a place to either copy directly or modify. The post provision script expects to run a puppet/shell/custom/post-provision.sh file if it exists. You can copy example-drupal-post-provision.sh to post-provision.sh, and it will perform the following actions:
- Copy settings.vm.php to settings.php -- if it's writeable
- Copy htaccess.dev to .htaccess -- necessary for projects running on Apache
- Create ~/.drush directory
- Copy any aliases in the root checkout to ~/.drush directory
- Create a ~/.drush/drush.ini file setting the memory_limit to 512M
