### ISSUE TITLE
Keep drush files inside the project root

### ISSUE THREAD

**Issue by ohthehugemanatee** [forumone/web-starter#35]
Right now the drush alias file in the project root is important to deployment... but that's an unintuitive location. Worse, we copy the alias file from there to the user's ~/.drush directory, where no one is expecting project files to end up. We also sneakily set the user's global ~/.drush/drush.ini. This is poor practice: we should keep the project scope within the project directory!

Since [webroot]/sites/all/drush is a standard and valid location for the alias file, we should simplify the post-deploy script, and store the drush aliases file there.  

We don't have to set the php memory_limit in ~/.drush/drush.ini . We can also set it in sites/default/drushrc.php . This is a much more intuitive location, and it's in the repo!

**Comment by ohthehugemanatee** [comment]
Actually, since I last looked at it we can now put drushrc.php in sites/all/drush as well. That's even better!

**Comment by ohthehugemanatee** [comment]
@azinck commented in Hipchat: "trouble with keeping them in the site repo is that the aliases that reference vagrant boxes have an ssh-options setting containing a path that I don't think can be generalized for all people "

It's the path to Vagrant's generated private key. In earlier versions of Vagrant (until Dec 2015 or so) it was stored in ~/.vagrant/insecure_private_key . Now it's stored inside the project root. I put the following at the top of my aliases file and it works for all my projects and both machines:

``` php
// Figure out where the vagrant private key is stored (it moved in a recent Vagrant version)
$local_root = drush_get_context('DRUSH_SELECTED_DRUPAL_ROOT');
$new_keyfile_path =  $local_root . '/../.vagrant/machines/default/virtualbox/private_key';
if (is_file($new_keyfile_path)) {
  $insecure_private_key = $new_keyfile_path;
}
else {
  $insecure_private_key = '~/.vagrant.d/insecure_private_key';
}

$aliases['local'] = array(
  'parent' => '@parent',
  'uri' => 'http://10.11.12.14',
  'root' => '/vagrant/public',
  'remote-host' => '10.11.12.14',
  'remote-user' => 'vagrant',
  'ssh-options' => "-i " . $insecure_private_key . " -l vagrant",
  'db-url' => 'mysql://web:web@10.11.12.14:3306/web',
  'databases' => array (
    'default' => array (
      'default' => array (
        'database' => 'web',
        'username' => 'web',
        'password' => 'web',
        'host' => '10.11.12.14',
        'port' => '',
        'driver' => 'mysql',
        'prefix' => '',
      ),
    ),
  ),
);
```

**Comment by azinck** [comment]
Ah, wasn't aware of the drush_get_context option to get the drupal root.  Nice!

**Comment by azinck** [comment]
also: FWIW, vagrant switched where the private key is stored far, far longer ago than December 2015.  Might have been more like Dec. 2014.  I'm guessing you just recently updated vagrant :).

**Comment by ohthehugemanatee** [comment]
hehehehe guilty as charged! :)

On Mon, Jan 11, 2016 at 4:07 PM azinck notifications@github.com wrote:

> also: FWIW, vagrant switched where the private key is stored far, far
> longer ago than December 2015. Might have been more like Dec. 2014. I'm
> guessing you just recently updated vagrant :).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/forumone/web-starter/issues/35#issuecomment-170581397
> .
> 
> ## 
> 
> _Campbell Vertesi_
> Technical Architect, Lead Evangelist

campbell@forumone.com
+49 151 46621809 (EU)  |  +1 (347) 329-4511 (US)
www.forumone.com
drupal.org/u/ohthehugemanatee https://www.drupal.org/u/ohthehugemanatee
twitter.com/campbellvertesi

_Forum One:_ Extend your influence

**Comment by arh1** [comment]
I know that -- this issue aside -- we've adopted the approach above to finding the VM's SSH key, as in our [example site.aliases.drushrc.php](https://github.com/forumone/web-starter/blob/f62c46a80768bc1377e69a93be2f6c48b2ec9bf1/examples/drupal/site.aliases.drushrc.php).

This approach isn't working for me anymore after switching from an old Vagrant to 1.8.1 (and to Drush 8). If I use a local (VM) drush alias from my host machine, the key is not located and I'm prompted for a password. The key file is located in the expected location, but `drush_get_context('DRUSH_SELECTED_DRUPAL_ROOT')` returns an empty array. 

I'm not finding good docs about this yet... Where does DRUSH_SELECTED_DRUPAL_ROOT get defined? Has this behavior changed in Drush 8? Is there a better way to find the project/key path dynamically on the host machine?
