### ISSUE TITLE
Drupal setup script

### ISSUE THREAD

**Issue by ohthehugemanatee** [forumone/web-starter#36]
Write an interactive bash setup script which converts web-starter into a ready-to-go new development site. 

The script should:
- rename the git web-starter remote to web-starter, to simplify pulling future updates.
- optionally get the new site's repo address and add the remote.
- Get the project name and update capistrano deployment
- optionally download Drupal-latest
- Get the project's dev, staging, and live URLs and SSH usernames, and set up:
  - deployment .rb files
  - drush aliases file (either copied into sites/all/drush or examples/sites/all/drush)
- set up drushrc.php either in sites/all/drush or examples/sites/all/drush
- Optionally get the project's staging and live DB credentials, and set up sites/default/settings.*.php
- Copy the custom post-deploy script into place.
- Create a logfile of setup steps taken.

I hope I'm not missing anything. :) This should all be done without committing any changes to the repo. The site admin may want to make customized changes on their own before the first commit. The idea is to make this useful for converting an existing site OR setting up a new site.

**Comment by wwhurley** [comment]
I've started a stub of a Yeoman generator at forumone/generator-web-starter. I'll be adding the bullet points from this as issues on that project.
