### ISSUE TITLE
Hangs on 'Waiting for machine to boot' running 'vagrant up' for the first time

### ISSUE THREAD

**Issue by lrobeson** [forumone/web-starter#40]
Running `vagrant up` for the first time, within the web-starter directory, on the 1.1.x branch. 

﻿﻿`==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!`

**Comment by wwhurley** [comment]
The "Connection timeout" message is expected. Vagrant will attempt to connect to the machine periodically but until the VM boots sufficiently to start sshd it is unable to verify that the machine started correctly. Depending on host resources this may cause multiple messages as you've seen.
