### ISSUE TITLE
Puppet issues running 'vagrant up' for the first time

### ISSUE THREAD

**Issue by lrobeson** [forumone/web-starter#41]
Running `vagrant up` for the first time, within the web-starter directory, on the 1.1.x branch. _(Feel free to update the title of this issue, I'm not really sure what the main issue is.)_

Debug info/dump: http://hastebin.com/ovobobaxet.coffee

**Comment by wwhurley** [comment]
At present Puppet is set to output all debugging messages. The majority of these are probably unnecessary for the general user.

**Comment by lrobeson** [comment]
Okay sorry, wasn't sure if you wanted us to be filing issues or not and it's hard to tell what's expected and what's an actual problem.

**Comment by wwhurley** [comment]
Always like more issues. Can always respond or close them as appropriate :).
