### ISSUE TITLE
Automatically cd to /vagrant/public directory after SSHing into the VM

### ISSUE THREAD

**Issue by lrobeson** [forumone/web-starter#42]
Is there an easy personal config change that can make this happen?

**Comment by lrobeson** [comment]
I figured out a way to do this: https://coderwall.com/p/oooszg/vagrant-tweaks-to-make-it-more-like-your-local-command-line-app. Basically just add `cd /vagrant/public` at the bottom of `/home/vagrant/.bashrc`.

**Comment by ohthehugemanatee** [comment]
drush @project.local ssh
