### ISSUE TITLE
Extract Capistrano Target/Environment List From /lib

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#48]
Currently if I want to define a different list of deployment targets for Capistrano, I have to edit `/lib/capistrano/install.cap` lines 3 and 5. It looks like there's currently the option to define the list in an environment variable, but could this be extracted into a project-specific config file to ensure consistency between installations that doesn't require documenting a specialized step of setting an environment variable before installation.

_Note_: Flagging this as a question as well as an enhancement for clarification if I'm just overlooking something.

**Comment by wwhurley** [comment]
Do you mean a different set of stages, e.g. dev, stage, production? Or different set of roles, e.g. web, db, app?

**Comment by slucero** [comment]
I'm looking specifically at the stages or deployment environments. An example is if a project requires a fourth environment added to the list to look like: dev, preview, stage, production.

In this case "preview" is the new addition, but ideally this and any further additions could be more easily defined.

**Comment by wwhurley** [comment]
You just add another file to the config/deploy directory with the [stage].rb name. So you'd have a config/deploy/preview.rb file with the same information that you find in the other stages. Once you create the file you can run `bundle exec cap preview deploy`
