### ISSUE TITLE
Error installing Mailcatcher: requires i18n, which requires Ruby >= 1.9.3

### ISSUE THREAD

**Issue by ohthehugemanatee** [forumone/web-starter#49]
ACTIAC had trouble running vagrant provision. Looks like i18n now requires a higher ruby version. From the vagrant output: 

`==> default: Notice: /Stage[main]/Forumone::Mailcatcher/Package[tilt]/ensure: cr
eated
==> default: Error: Execution of '/usr/bin/gem install --include-dependencies --
no-rdoc --no-ri mailcatcher' returned 1: ERROR:  Error installing mailcatcher:
==> default:    i18n requires Ruby version >= 1.9.3.
==> default: INFO:`gem install -y`is now default and will be removed
==> default: INFO:  use --ignore-dependencies to install only the gems you list
==> default: Error: /Stage[main]/Forumone::Mailcatcher/Package[mailcatcher]/ensu
re: change from absent to present failed: Execution of '/usr/bin/gem install --i
nclude-dependencies --no-rdoc --no-ri mailcatcher' returned 1: ERROR:  Error ins
talling mailcatcher:
==> default:    i18n requires Ruby version >= 1.9.3.
==> default: INFO:`gem install -y`is now default and will be removed
==> default: INFO:  use --ignore-dependencies to install only the gems you list
==> default: Notice: /Stage[main]/Forumone::Mailcatcher/File[/etc/init.d/mailcat
cher]: Dependency Package[mailcatcher] has failures: true`

Then it fails since SSH returned 1.

**Comment by mortona42** [comment]
I'm also running into this.
