### ISSUE TITLE
Way to bypass/remove password prompt when booting VM?

### ISSUE THREAD

**Issue by lrobeson** [forumone/web-starter#50]
Sometimes I run `vagrant up` and then look at another screen or window and don't always see the password prompt. Is there a way to either remove the need for it or ask for it to be input at the very beginning of the boot process, when still looking at the screen?

I'm running Mac Yosemite, if that matters.

![](http://cl.ly/image/3Y3Z3m260q0q/Image%202014-12-31%20at%208.45.07%20AM.png)

**Comment by wwhurley** [comment]
Unfortunately sudo is required to modify the NFS exports file. If we were to not use NFS then it wouldn't be necessary, but file system operations would be significantly affected.
