### ISSUE TITLE
Installed Git Version is Outdated

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#6]
I'm seeing the installed version of Git on the virtual machine as version 1.7.1. It looks like the latest version is 1.9.2. Is there a reason this is installing such an old version and would this be something we could update?

**Comment by wwhurley** [comment]
We typically use the repository version of packages unless there is a compelling reason not to. Since most git commands should be executed on the host OS to avoid having commits that come from the user vagrant, I'm not sure this is a significant issue.
