### ISSUE TITLE
Vagrantfile.local for local development

### ISSUE THREAD

**Issue by lrobeson** [forumone/web-starter#67]
**Problem:**
Every developer has their own preferred tools/settings for local development, but there's currently no "approved" way (that I'm aware of) to make those modifications.

I understand environment consistency is one of the main reasons for using Web Starter Kit, but I think it's important to allow for this kind of personalization because familiarity and little tweaks make for happier developers.

**Proposed solution:**
1) I like to add a synced folder to my Vagrant instances because it's an easy way to have shared configuration (primarily a single .bash_profile) across VMs. I've added this to the Vagrantfile for my projects:

```
overrides = "#{__FILE__}.local"
if File.exist?(overrides)
   eval File.read(overrides)
end
```

2) This allows me to use a Vagrantfile.local which contains my extra local configuration:

```
Vagrant.configure("2") do |config|

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder "/Users/ldavis-robeson/Google\ Drive/Local\ Dev/vagrant-shared", "/home/vagrant"

end
```

3) The new Vagrantfile.local file would have to be added to .gitignore

Tip: it would be helpful to reiterate that the local file only needs to override or add to default settings. I mistakenly copied the entire contents to my local file and then had issues when major changes were made to the project's default settings.

**Comment by arh1** [comment]
I didn't know about the syntax to mount an additional folder -- thanks!

But by default you can include a Vagrantfile.local with overrides for the default Vagrantfile .  (And Vagrantfile.local should already be in .gitignore .) So I'm not sure there are any changes needed here?

**Comment by arh1** [comment]
Oops, meant to link to the documentation... See "Local Overrides": http://forumone.github.io/web-starter/localdev/vmoptions.html

**Comment by slucero** [comment]
@lrobeson, I'm pretty sure @arh1 is right with what he noted above. On the 1.1.x branch this feature was added in 5b9b1feb.

https://github.com/forumone/web-starter/blob/1.1.x/Vagrantfile#L100-L103

If you're projects aren't including this by default it may be that they haven't resynced with the latest releases for a bit.

**Comment by lrobeson** [comment]
Aha, indeed, there it is.

I've never seen that https://forumone.github.io/web-starter/localdev/vmoptions.html page before, thanks! I tend to habitually go to the README info on the GH page, shouldn't the info there be the same as what's on the github.io site?

**Comment by arh1** [comment]
Yeah, that documentation hasn't been widely circulated, unfortunately.  I'll send a note out about that now!
