### ISSUE TITLE
Feature Request: Utility Tasks for Local Management

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#70]
## Background

Most of the workflow tasks for maintaining a local copy of the site are currently manageable using the tools available, but there are still some repetitive tasks that are multi-step processes that might benefit from being aggregated together in some utility to be run locally.
## Benefit

Providing tools to abstract multi-step processes everyone might not be familiar with provides general users with shortcuts and tools to do more with less effort while providing power users with a framework for building out more custom and complex tasks in their projects as needed.
### Rake

An advantage of aggregating these in Rake vs other options is that depending on the task being performed, it may also be applicable to remote deployments and could be reused via Capistrano.
### Grunt

Grunt is already integrated into the project and is more familiar and accepted than Rake by our user base.
## Example Tasks
- Database synchronization
  - Sync database with other environments
  - Database snapshots
- Changing collections of development settings and/or enabled modules
  - Toggle development modules
  - Toggle development settings in the database
  - Change local configuration to more closely mimic a specific environment
- Configuration changes on the host machine
  - Install Drush aliases for access outside the VM
- Service management on the virtual machine
- Configuration changes on the virtual machine
- Update to latest project work
  1. Pull latest code
  2. Apply database updates/migrations
  3. Revert features (if applicable)

**Comment by wwhurley** [comment]
Should we use Rake for this or Grunt?

**Comment by slucero** [comment]
When I've envisioned changes like this in the past I've always leaned more toward using Grunt, but after working with Rake a bit more this week I see a fair bit of utility there as well.

At the risk of incomprehensibly dividing our tool sets I'd say that depending on the task it may fit in one place more clearly than the other. For example, for most of our types of projects I would keep the asset pipeline in Grunt, but for tasks bridging multiple systems, like database manipulation tasks or restarting services on the vm, Rake might be more appropriate.

In case it's not evident from the train-of-thought style of reasoning, this is definitely still an idea in conceptual stages.

**Comment by slucero** [comment]
Maybe a better approach would be to generalize this feature request to focus more on just having a utility for local tasks and determining which tool to use based on what type of tasks we come up with?

**Comment by slucero** [comment]
Relabeled and edited the ticket to focus more on the problem than a dictated solution.
