### ISSUE TITLE
Pattern Lab Integration

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#73]
Integrate setup and usage of [Patternlab](http://patternlab.io/) with projects. Potentially add integration specifically for [dcmouyard/patternlab-php-gesso](https://github.com/dcmouyard/patternlab-php-gesso) on Drupal-specific projects.

**Comment by coreylafferty** [comment]
I've done some work on this, in terms of the Grunt configuration.  If it'd help you can see the work on this branch (https://github.com/coreylafferty/patternlab-php-gesso/tree/grunt-config) and integrated into a project on GIExchange (https://github.com/forumone/DAI-USAID)

**Comment by lrobeson** [comment]
Some of us met last week to discuss where Pattern Lab should "live" in a project, I think having a better idea of that will help push this issue forward.

Also, we should be able to add the build process to CI, which would get rid of the public directory headache at least: http://peterwilson.cc/pattern-lab-post-merge-hook/

Bonus points if we can get rid of the source/css files too!

**Comment by wwhurley** [comment]
We've updated NRGI to use grunt to build and sync the files from /patternlab to the theme directory. Also added the public and source/css directories to .gitignore. Though it seems some of this is going to be changed again when we re-visit placement of the Patternlab files.

**Comment by lrobeson** [comment]
Awesome! It should hopefully get simplified because I believe we're going to put PL _in_ the theme directory.

**Comment by wwhurley** [comment]
One thing to note is that Patternlab requires PHP >= 5.3.6 where RHEL (and derivatives) have PHP 5.3.3 by default. So by having this run at build time we add additional requirements to the build environment.

**Comment by dcmouyard** [comment]
The Gesso version of Pattern Lab is now setup to be placed directly in the theme directory.

Is there anything we can do during setup to have the `gesso/pattern-lab/public/` directory publicly accessible by default?
