### ISSUE TITLE
Drupal settings file permissions

### ISSUE THREAD

**Issue by johnbburg** [forumone/web-starter#75]
Drupal best practices suggest that the settings file directory should be read-only (https://www.drupal.org/documentation/install/settings-file). Usually, Drupal will reset these permissions when it is able to, but a best practice is to restrict the web-servers write access to the site's executable files. Currently the Web-starter package's build scripts leave these permissions **as is** after build. This causes warnings in the site reports page to show:

> The directory sites/default is not protected from modifications and poses a security risk. You must change the directory's permissions to be non-writable. The file sites/default/settings.php is not protected from modifications and poses a security risk. You must change the file's permissions to be non-writable.

This issue is to update the Drupal build script to update settings file and directory permissions during build to comply with Drupal's best practices.

Note, the script that removes old builds already updates permissions so they are write-able before removal, so no action is necessary there.

**Comment by ohthehugemanatee** [comment]
This causes problems with  when you revision files inside sites/default,
like for example settings.php versions for different environments.

We could resolve this problem by moving settings.php versions outside of
the doc root entirely. Would make more sense anyway!
Am 07.05.2015 11:04 schrieb "John" notifications@github.com:

**Comment by johnbburg** [comment]
The change still expects settings files to be revision-ed with environment specific versions named in our current convention (settings.dev.php, settings.stage.php, settings.production.php). This change simply adds a chmod command that updates the file and directory permissions after a symlink pointing to the appropriate settings file is created.

**Comment by wwhurley** [comment]
We could move the settings files out of the webroot, but it really wouldn't make a difference. Either way we need to chmod them on the server because we can't trust the permissions in the VCS. It would just mean we would need either more directories or another naming convention for the settings files.
