### ISSUE TITLE
SSH / NFS issue after deleting unrelated site directory

### ISSUE THREAD

**Issue by lrobeson** [forumone/web-starter#85]
After moving a site directory for a project I'm no longer working on, I ran into problems on a still active site. I was able to SSH into the VM, but the `/vagrant` directory was completely empty. 

I tried running `vagrant provision` because I know that sometimes clears up random errors, which resulted in this:

```
==> default: Running provisioner: shell...
    default: Running: /var/folders/lh/_jt8k_w96gv27h2j07j7_6lm0000gq/T/vagrant-shell20150608-10949-1b0xzph.sh
==> default: /home/vagrant/.bashrc: line 13: cd: /vagrant/public: No such file or directory
==> default: Running provisioner: shell...
    default: Running: /var/folders/lh/_jt8k_w96gv27h2j07j7_6lm0000gq/T/vagrant-shell20150608-10949-12bfl1m.sh
==> default: /home/vagrant/.bashrc: line 13: cd: /vagrant/public: No such file or directory
==> default: /bin/bash: /vagrant/puppet/shell/os-detect.sh: No such file or directory
==> default: /bin/bash: /vagrant/puppet/shell/os-detect.sh: No such file or directory
==> default: cp:
==> default: cannot stat `/vagrant/puppet/Puppetfile'
==> default: : No such file or directory
==> default: cp:
==> default: cannot stat `/vagrant/puppet/Puppetfile.lock'
==> default: : No such file or directory
==> default: Copied Puppetfile
...
Shared folders that Puppet requires are missing on the virtual machine. This is usually due to configuration changing after already booting the machine. The fix is to run a `vagrant reload` so that the proper shared folders will be prepared and mounted on the VM.
```

I followed those instructions and ran 'vagrant reload', which gave me this:

```
NFS is reporting that your exports file is invalid. Vagrant does this check before making any changes to the file. Please correct the issues below and execute "vagrant reload":

exports:2: path contains non-directory or non-existent components: /Users/ldavis-robeson/Sites/BradyCenter
exports:2: no usable directories in export entry
exports:2: using fallback (marked offline): /
```

I found [this post](http://amygroshek.com/wp/vagrant-nfs-export-file-invalid/) and was able to fix the issue by running:
- `vagrant halt`
- `sudo rm -rf /etc/exports`
- `vagrant up`

This was especially confusing because Vagrant wasn't running in the site directory I deleted, I only have one VM running at a time or my machine explodes. Just wanted to submit this in case anyone runs into similar problems.

**Comment by wwhurley** [comment]
If you do a vagrant suspend Vagrant leaves the NFS exports in place. These are full paths to the shared location. So if you move the host directory NFS will still try and connect to the previous location and fail. When launching a VM nfsd attempts to verify the validity of the /etc/exports file, which is in an invalid state due to trying to map a directory that no longer exists. If you want to move a directory that you are no longer working on for whatever purpose in your personal workflow you need to ensure it is no longer running. To do so run "vagrant halt" and consider running "vagrant destroy" if you know you aren't going to be working on it for some time.

**Comment by lrobeson** [comment]
As a front end developer I don't know the ins and outs of Vagrant well enough to know all the implications of using `suspend` version `halt`, so this was an obscure thing for me to troubleshoot. Especially since the symptoms showed up on a completely unrelated project. There doesn't seem to be any mention of this error in the Troubleshooting documentation, which is why I filed this issue, it's a usability concern.
