### ISSUE TITLE
Documentation: Project Setup with Yeoman Generator

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#87]
What are the options and best practices for starting a new project based on the web-starter kit?
- [x] Using yeoman generator (forumone/generator-web-starter#14)
- [x] Git remote clone/pull (not recommended)
- [x] Configuring the project

**Comment by arh1** [comment]
Working notes are here, but need to be expanded and clarified:
https://github.com/forumone/generator-web-starter/blob/master/README.md

**Comment by slucero** [comment]
Related [project setup documentation](https://docs.google.com/a/forumone.com/document/d/1GOSZSVm3XY42ykn1fbhiPpvlXUNqIe32sG-uIroFd-A/edit?usp=sharing) (Google Drive: F1 Restricted).

**Comment by slucero** [comment]
> - Using yeoman generator (forumone/generator-web-starter#14)
> - Git remote clone/pull (not recommended)

See draft of instructions in the wiki: [Creating a project](https://github.com/forumone/web-starter/wiki/Creating-a-project)

**Comment by slucero** [comment]
Assigning to @wwhurley for a review of the draft.

See draft of instructions in the wiki: [Creating a project](https://github.com/forumone/web-starter/wiki/Creating-a-project)

**Comment by wwhurley** [comment]
Made some minor changes to the yeoman command. Otherwise everything else looks good. Of course the documentation for installing the generator itself needs to be updated.

**Comment by wwhurley** [comment]
Can you take a look at this @arh1 or @azinck?
