### ISSUE TITLE
Document the process of updating web-starter and generator on vagrant box

### ISSUE THREAD

**Issue by KalpanaGoel** [forumone/web-starter#89]
I am working on a redmine task which requires to add SSL support for web-starter. I was pointed to https://github.com/forumone/puppet-forumone/pull/7 and follow readme instructions https://github.com/forumone/generator-web-starter. I ran into some issues while trying to get yeoman and it threw an error node.js is outdated. http://privatepaste.com/f6d764651f, http://privatepaste.com/cd1c6a1ec7 are my terminal session output. Me and some other devs discussed on hipchat that we need some documentation for web-starter or anything to update on VM.

**Comment by slucero** [comment]
To begin with you'll need to make sure the web starter is installed globally on your machine through `npm`. To do this you'll need to run:

```
sudo npm install -g generator-web-starter
```

After installing the generator you'll need to update your project by re-running the generator from inside the project directory with the following:

```
yo web-starter:app
```

This will walk you through a series for prompts to help with configuration. If you originally setup the project with the generator it should already have the values you selected before pre-filled. If not then you'll need to compare the installed configuration through version control to determine which is correct and should be used.

Following completion of this you'll need to re-provision your vagrant machine:

```
vagrant reload --provision
```

**Comment by slucero** [comment]
Related: #91

**Comment by slucero** [comment]
I've captured this documentation in the forumone/generator-web-starter wiki: [Installation](https://github.com/forumone/generator-web-starter/wiki/Installation). Additionally, more comprehensive documentation was written in the web-starter wiki ([Using the Project Generator](https://github.com/forumone/generator-web-starter/wiki/Installation)) as a result of #91 and #89.
