### ISSUE TITLE
Documentation: Updating an existing project

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#91]
After a project has already been started and is under way, how should updates to the web-starter kit be pulled in?
- [x] Using the web-starter generator (forumone/generator-web-starter#16)
- [x] Remote repository and merging

**Comment by slucero** [comment]
> - Using the web-starter generator (forumone/generator-web-starter#16)
> - Remote repository and merging

See documentation draft in the wiki: [Creating a project](https://github.com/forumone/web-starter/wiki/Creating-a-project#using-the-project-generator)

**Comment by wwhurley** [comment]
Covered by changes to #87.
