### ISSUE TITLE
Documentation: Developer documentation and resources

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#93]
If someone wants to improve and contribute back to the project we should document as well as possible what they're diving into and where to get help to lower the barrier of entry.
- [x] Tools and languages being used
  - Vagrant
    - Puppet
      - Librarian
  - Grunt
  - Capistrano
    - Rake
  - SASS
- [x] Dependencies and interrelations
  - [forumone/generator-web-starter](https://github.com/forumone/generator-web-starter)
  - [forumone/puppet-forumone](https://github.com/forumone/puppet-forumone)
- [x] Project organization
- [x] Process sequences/workflows and summaries
- [ ] Helpful resources

**Comment by slucero** [comment]
Stubbed out a wiki page [here](https://github.com/forumone/web-starter/wiki/Developer-Documentation-and-Resources).

**Comment by wwhurley** [comment]
Can you take a look at what I put in on the wiki page and let me know if that's what you were thinking? Thanks.

**Comment by slucero** [comment]
That is **exactly** what I had in mind. You rock!

@arh1 or @azinck, if you get a chance could you skim through this for review?
[Developer Documentation and Resources](https://github.com/forumone/web-starter/wiki/Developer-Documentation-and-Resources)

**Comment by azinck** [comment]
Looks very very good. Some minor feedback from skimming it:
- Step 4 of "Building the local development environment" says "Run Puppet provisioner".  Can you provide more context on what's actually going on here?  Is there a configuration file this step specifically uses?  
- Building on my last comment: In general, mapping each step to relevant configuration files would be very helpful.  You can kind of piece it together from what's here, but it would take some detective work for someone less familiar with the system.
- For both the "Deploying the project" and the "What Jenkins does" sections it would be very helpful to make explicit _where_ each of these commands is executed.  Which are done locally, which are done on the destination.  Similarly, it would be great to explicitly tie these steps to the relevant config files.

**Comment by arh1** [comment]
Yeah, this is really helpful, and the kind of reference I've heard many folks requesting for a while now -- nice work!

One thing I'm a little unclear on (b/c I haven't been able to successfully build a project w/ the new generators yet, pending an issue I filed and more poking) is what files might optionally be edited for customization after the generator runs (e.g. custom shell provisioners? grunt tasks?). (See notes like we have in the [Grunt tasks readme](https://github.com/forumone/web-starter/blob/1.1.x/tasks/README.md).)

That might best be handled by a separate page that's a follow up to  [Creating a project](https://github.com/forumone/web-starter/wiki/Creating-a-project), but the breakdown of the directory structure and files reminds me that it's not obvious _which_ files are candidates for customization.

**Comment by wwhurley** [comment]
Generally speaking if the file is templated out by Yeoman and is modified after the fact those changes will need to be reconciled. However I'm hesitant to put too much into other files since changes to them need to be manually modified for each project, so pushing out changes becomes a significant challenge.

**Comment by johnbburg** [comment]
It seems that adding "Helpful resources" is what's holding up this issue. The developer documentation itself seems to be a helpful resource on it's own. So to move this along, we either need to:

Determine what "Helpful Resources" are worth adding in https://github.com/forumone/web-starter/wiki/Developer-Documentation-and-Resources#helpful-resources. Which may include:
- Links to documentation for other tools used in web-starter - Already done on this page.
- Documentation on the tool itself - I think it could use improvement in specific areas for sure, but this is present  as the page stands. I think we should opt to create individual issues that focus on specific sections for documentation.
- Examples - None here, but that's generally what http://forumone.github.io/web-starter/ provides.

Or Decide if the existing documentation sufficiently covers what is needed.

Given the open-ended nature of this remaining task. I think we can close this and try to focus on more specific areas on how we can improve web-starter's documentation.
