### ISSUE TITLE
Documentation: Creating and Modifying Grunt Tasks

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#95]
An upcoming change in #61 will change the way Grunt tasks are organized and the vision for how they should be managed. With the introduction of this change we need to document the path forward for users making changes to existing task configurations and introducing new tasks.
- [x] What is grunt and what does it do for us?
- [x] How are grunt tasks and registrations organized?
- [x] How to adjust configuration for existing tasks?
- [x] How to add and configure new tasks and plugins?

Related to developer documentation (#93).

**Comment by lrobeson** [comment]
Phase2's Pattern Lab Starter project has an interesting Grunt setup: https://github.com/phase2/pattern-lab-starter/blob/master/Gruntfile.js. It's definitely not simplified but might have some options we haven't thought of yet.

Is the goal here to have a single Gruntfile for a project, including front end tasks? I'm in favor of simplifying and streamlining configuration, for sure, and I'm constantly tweaking my own Grunt setup, so let me know if I can help with this at all.

**Comment by slucero** [comment]
> Is the goal here to have a single Gruntfile for a project, including front end tasks?

@lrobeson, the work that was merged in from #61 introduced a new organization for the grunt files and their configuration. One of the main ideas is that the core Gruntfile becomes more boilerplate and shouldn't require customization in most projects. Instead new tasks and their configuration are added independently in the `/tasks/config/` and `/tasks/register` folders. Below is an excerpt from the [Readme](https://github.com/forumone/web-starter/blob/1.1.x/tasks/README.md) there which is currently the best documentation we have on the process.

> You can modify, omit, or replace any of these Grunt tasks to fit your requirements. You can also add your own Grunt tasks- just add a `someTask.js` file in the `grunt/config` directory to configure the new task, then register it with the appropriate parent task(s) (see files in `grunt/register/*.js`).
> 
> I'm in favor of simplifying and streamlining configuration, for sure, and I'm constantly tweaking my own Grunt setup, so let me know if I can help with this at all.

Ideally this framework will make the process of adding and customizing grunt tasks more straightforward and, most importantly, sharable between projects. To this end I believe @ohthehugemanatee has already started working on some pattern-lab task configuration to be shared, so feel free to reach out to him about some of that work or tackle some of the other tasks that'll be useful across projects. I'm pretty sure you have a lot of experience setting up some of the various front-end utilities through grunt, so I think there could be a lot to gain in that direction if you were interested.

**Comment by slucero** [comment]
Below is a related update from @wwhurley about changes to the build process introduced in #61 and #99. 

> With some recent changes to the structure of the Grunt build process the invocation will also be changing. There will now be two entry-points to the build process:
> 1. grunt build -- triggers the complete build process
> 2. grunt -- triggers the complete build process and then any file watches
> 
> The reason this may be a breaking change is that some Jenkins jobs may be using `grunt` and will need to changed to `grunt build` if the project is updated to use these new Grunt tasks.
> 
> The expectation is that a developer on a project will be able to run `grunt` after cloning the repo and provisioning the VM and then any changes to the file system that are important will be handled automatically. If they need to simply build the project one time it would be `grunt build`.

**Comment by azinck** [comment]
This documentation is now out of date: http://forumone.github.io/web-starter/deployment/grunt.html

**Comment by wwhurley** [comment]
@lrobeson could you review the documentation found at https://github.com/forumone/web-starter/wiki/Build-process and let me know if it makes sense or if there's anything you feel is missing? Thanks.

**Comment by lrobeson** [comment]
@wwhurley Looks great! Definitely an improvement over the single file setup in place before.

If you want me to be super picky, I'd change "SASS" to "Sass", but that's it.

**Comment by wwhurley** [comment]
Change made. Thanks. We'll be adding this to the GH pages documentation as soon as we do some cleanup of that project.
