### ISSUE TITLE
Documentation: Improve Readme

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#96]
The project readme hasn't been updated in a while and could benefit from being retouched to add in a few new points including:
- Project goals and features
- Project relationship and usage with [forumone/generator-web-starter](https://github.com/forumone/generator-web-starter) (#87 & #91)
- Getting support when things go wrong (#88)
- Contribution (#88)

**Comment by lrobeson** [comment]
I'd like to request that some additional instructions be added to the "Getting Vagrant environment set up" section. I have yet to use this on a project where the Tech Lead didn't have to get involved to get everything working. There are always database and/or settings.php and/or file permission issues and it's really frustrating.
