### ISSUE TITLE
Feature Request: Capture Deployment and Build Scripts in Version Control

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#97]
Currently scripts for building and deploying a project through automated deployment are not captured. The commands are usually simple, but clarifying and capturing that process with the rest of the deployment process would facilitate any needed complexity uniquely needed in projects.

**Comment by ohthehugemanatee** [comment]
I don't understand... can you give an example? what steps aren't captured?

**Comment by slucero** [comment]
Our deployment jobs typically run a couple of shell execution steps: build and post-build (deployment). Typically these are pretty consistent and simple, but over the course of various projects I have found scenarios where these need to be altered from the norm.

Currently these tasks are not captured within the project at all and the process for these tasks isn't documented anywhere aside from the configuration of the actual task in a separate system. If the interface for these tasks is more standardized then the jobs in Jenkins or any other deployment system can become more consistent and templated to require less customization per project and less error-prone. At the same time, these default behaviors can be prepopulated in the build and deployment scripts so that most projects never need to alter them, but the system is in place when a project does need to.

Also, given that these tasks are reasonably common scenarios, even outside of Jenkins or similar, this encapsulation could be rolled into the work described in #70.

**Comment by wwhurley** [comment]
Can you give examples of the sort of tasks you end up putting into bash scripts?

**Comment by slucero** [comment]
There's also room for these tasks and the deployment process to become more robust which would further encourage this type of version control and documentation. An example of where this process could become more complex is the work in #78.

**Comment by slucero** [comment]
The most complex scenario I've encountered was in the USWP project where our repository was being mapped onto the remote Pantheon repository during deployment.

**Comment by wwhurley** [comment]
I believe this would be covered by Jenkins Job Builder described in #122.
