### ISSUE TITLE
File permission-related errors while provisioning Solr 3.6.2

### ISSUE THREAD

**Issue by azinck** [forumone/web-starter#98]
In case it's important (actually, I suspect it is), I used the latest version of the generator-web-starter project to generate a configuration using Solr and the latest (1.1.x) version of web-starter.  Upon running vagrant up I get a host of errors, the first, and apparently most relevant, one being:
`default: Error: tar -zxvf /tmp/vagrant-cache/apache-solr-3.6.2.tgz -C /opt returned 2 instead of one of [0]`

SSHing into the box, I was able to resolve this problem by deleting the /opt/apache-solr-3.6.2 in its entirely, and running `sudo tar -zxvf /tmp/vagrant-cache/apache-solr-3.6.2.tgz -C /opt` which successfully extracted the archive with no errors.  I then ran vagrant provision on the host machine and provisioning completed successfull without errors.

**Comment by wwhurley** [comment]
I'm unable to replicate this issue. Have you seen this on other projects?

**Comment by azinck** [comment]
I haven't...but I haven't tried starting up any other projects since Kresge.
